### ISSUE TITLE
Error while running Astor

### ISSUE THREAD

**Issue by Somdutta** [SpoonLabs/astor#163]
Hi, 

I got the following error when I ran Astor:

[INFO ] fr.inria.astor.core.setup.ProjectConfiguration.getVersionJDK(ProjectConfiguration.java:282) - Version of the JVM used: 1.8.0_212
[INFO ] fr.inria.main.AbstractMain.processArguments(AbstractMain.java:370) - Java version of the JDK used to run tests: 1.8.0_212
[INFO ] fr.inria.main.AbstractMain.processArguments(AbstractMain.java:371) - The compliance of the JVM is:  8
[INFO ] fr.inria.main.AbstractMain.processArguments(AbstractMain.java:645) - command line arguments: [-mode  jkali  -location  /Users/somdutta/astor/examples/math_70  -mode  jMutRepair  -package  org.apache.commons  -failing  org.apache.commons.math.analysis.solvers.BisectionSolverTest  -srcjavafolder  /src/main/java/  -srctestfolder  /src/test/  -binjavafolder  /Users/somdutta/astor/target/classes  -bintestfolder  /Users/somdutta/astor/target/test-classes  -flthreshold  0.5  -stopfirst  true  -dependencies  /examples/libs/junit-4.4.jar /examples/libs/hamcrest-core-1.3.jar]
[INFO ] fr.inria.main.evolution.AstorMain.execute(AstorMain.java:216) - Running Astor on a JDK at /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:849) - Source folders: [/Users/somdutta/astor/examples/math_70/src/main/java]
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:868) - Source Test folders: [/Users/somdutta/astor/examples/math_70/src/test]
Exception in thread "main" java.lang.IllegalArgumentException: The bin folder  /Users/somdutta/astor/examples/math_70/Users/somdutta/astor/target/classes does not exist.
	at fr.inria.main.AbstractMain.determineBinFolder(AbstractMain.java:824)
	at fr.inria.main.AbstractMain.getProjectConfiguration(AbstractMain.java:795)
	at fr.inria.main.evolution.AstorMain.initProject(AstorMain.java:54)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:168)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:236)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:210)

The command that I ran from the Astor directory is:

java -cp /Users/somdutta/astor/target/astor-1.0.0-SNAPSHOT-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -mode jkali -location /Users/somdutta/astor/examples/math_70 -mode jMutRepair -package org.apache.commons -failing org.apache.commons.math.analysis.solvers.BisectionSolverTest -srcjavafolder /src/main/java/ -srctestfolder /src/test/ -binjavafolder /Users/somdutta/astor/target/classes -bintestfolder /Users/somdutta/astor/target/test-classes -flthreshold 0.5 -stopfirst true -dependencies /examples/libs/junit-4.4.jar,/examples/libs/hamcrest-core-1.3.jar

Thanks
Somdutta

**Comment by nju-grx** [comment]
Maybe you should try changing the parameters as follows:
-binjavafolder /target/classes
-bintestfolder /target/test-classes
This may help you.

**Comment by Somdutta** [comment]
I tried that before and also tried it again. I am getting the following error:


[INFO ] fr.inria.astor.core.setup.ProjectConfiguration.getVersionJDK(ProjectConfiguration.java:282) - Version of the JVM used: 1.8.0_212
[INFO ] fr.inria.main.AbstractMain.processArguments(AbstractMain.java:370) - Java version of the JDK used to run tests: 1.8.0_212
[INFO ] fr.inria.main.AbstractMain.processArguments(AbstractMain.java:371) - The compliance of the JVM is:  8
[INFO ] fr.inria.main.AbstractMain.processArguments(AbstractMain.java:645) - command line arguments: [-mode  jkali  -location  /Users/somdutta/astor/examples/math_70  -mode  jMutRepair  -package  org.apache.commons  -failing  org.apache.commons.math.analysis.solvers.BisectionSolverTest  -srcjavafolder  /src/main/java/  -srctestfolder  /src/test/  -binjavafolder  /target/classes  -bintestfolder  /target/test-classes  -flthreshold  0.5  -stopfirst  true  -dependencies  /examples/libs/junit-4.4.jar /examples/libs/hamcrest-core-1.3.jar]
[INFO ] fr.inria.main.evolution.AstorMain.execute(AstorMain.java:216) - Running Astor on a JDK at /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home/jre
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:849) - Source folders: [/Users/somdutta/astor/examples/math_70/src/main/java]
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:868) - Source Test folders: [/Users/somdutta/astor/examples/math_70/src/test]
Exception in thread "main" java.lang.IllegalArgumentException: The bin folder  /Users/somdutta/astor/examples/math_70/target/classes does not exist.
	at fr.inria.main.AbstractMain.determineBinFolder(AbstractMain.java:824)
	at fr.inria.main.AbstractMain.getProjectConfiguration(AbstractMain.java:795)
	at fr.inria.main.evolution.AstorMain.initProject(AstorMain.java:54)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:168)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:236)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:210)

**Comment by nju-grx** [comment]
Have you compiled this project? 
`cd examples/math_70`
`mvn clean compile`

**Comment by Somdutta** [comment]
Yes, the build was successful. But still I am getting the error  mentioned earlier.
