### ISSUE TITLE
log4j:ERROR setFile(null,true) call failed.

### ISSUE THREAD

**Issue by jose** [SpoonLabs/astor#226]
```
java.io.FileNotFoundException:  (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
	at org.apache.log4j.RollingFileAppender.setFile(RollingFileAppender.java:207)
	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
	at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:580)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
	at org.apache.log4j.Logger.getLogger(Logger.java:117)
	at fr.inria.astor.core.setup.ConfigurationProperties.<clinit>(ConfigurationProperties.java:16)
	at fr.inria.main.AbstractMain.<clinit>(AbstractMain.java:100)
```

**Comment by jose** [comment]
This might be due to the [underline nopol](https://github.com/SpoonLabs/astor/blob/master/pom.xml#L115) code and not to astor. (More on this [here](https://github.com/SpoonLabs/nopol/issues/199).)

**Comment by monperrus** [comment]
I can reproduce the bug with a minimal example:

```
java -cp /home/martin/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/martin/.m2/repository/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar:target/spoon-core-8.4.0-SNAPSHOT-jar-with-dependencies.jar:. foo
log4j:ERROR setFile(null,true) call failed.
```

The failure comes from the dependency to log4j version 1.2.x (aka log4j12) via slf4j-log4j12

Since log4j1.2 is not [supported anymore](http://logging.apache.org/log4j/1.2/index.html) since 2015, the workaround consists of correctly configuring the SL4J logging pipeline.
