### ISSUE TITLE
NPE when Astor aims printing some ingredient 

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/astor#6]

**Comment by martinezmatias** [comment]
java.lang.NullPointerException
	at spoon.support.reflect.reference.CtReferenceImpl.setSimpleName(CtReferenceImpl.java:70)
	at spoon.reflect.factory.TypeFactory.createReference(TypeFactory.java:151)
	at spoon.reflect.factory.TypeFactory.createReference(TypeFactory.java:148)
	at spoon.support.reflect.declaration.CtTypeImpl.getReference(CtTypeImpl.java:258)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtClass(DefaultJavaPrettyPrinter.java:801)
	at spoon.support.reflect.declaration.CtClassImpl.accept(CtClassImpl.java:59)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:444)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtNewClass(DefaultJavaPrettyPrinter.java:1648)
	at spoon.support.reflect.code.CtNewClassImpl.accept(CtNewClassImpl.java:31)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:444)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.writeLocalVariable(DefaultJavaPrettyPrinter.java:1397)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtLocalVariable(DefaultJavaPrettyPrinter.java:1404)
	at spoon.support.reflect.code.CtLocalVariableImpl.accept(CtLocalVariableImpl.java:49)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:444)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.writeStatement(DefaultJavaPrettyPrinter.java:2244)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtBlock(DefaultJavaPrettyPrinter.java:697)
	at spoon.support.reflect.code.CtBlockImpl.accept(CtBlockImpl.java:47)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:444)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.visitCtIf(DefaultJavaPrettyPrinter.java:1172)
	at spoon.support.reflect.code.CtIfImpl.accept(CtIfImpl.java:38)
	at spoon.reflect.visitor.DefaultJavaPrettyPrinter.scan(DefaultJavaPrettyPrinter.java:444)
	at spoon.support.reflect.declaration.CtElementImpl.toString(CtElementImpl.java:364)
	at fr.inria.astor.core.loop.evolutionary.JGenProg.alreadyApplied(JGenProg.java:425)
	at fr.inria.astor.core.loop.evolutionary.JGenProg.getFixIngredient(JGenProg.java:314)
	at fr.inria.astor.core.loop.evolutionary.JGenProg.createOperationForGen(JGenProg.java:216)
	at fr.inria.astor.core.loop.evolutionary.EvolutionaryEngine.modifyProgramVariant(EvolutionaryEngine.java:523)
	at fr.inria.astor.core.loop.evolutionary.EvolutionaryEngine.createNewProgramVariant(EvolutionaryEngine.java:434)
	at fr.inria.astor.core.loop.evolutionary.EvolutionaryEngine.processGenerations(EvolutionaryEngine.java:240)
	at fr.inria.astor.core.loop.evolutionary.EvolutionaryEngine.startEvolution(EvolutionaryEngine.java:122)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:161)
	at fr.inria.main.AbstractMain.executeExample(AbstractMain.java:388)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:184)
	at fr.inria.astor.test.repair.evaluation.JGenProgTest.testExample280CommandLine(JGenProgTest.java:85)

**Comment by martinezmatias** [comment]
Math-80, Math-8 
Printing: org.apache.commons.math.linear.MatrixUtils
