### ISSUE TITLE
ShortestIngredientSearchStrategy cause java.lang.ClassNotFoundException in command line but not in test

### ISSUE THREAD

**Issue by chenzimin** [SpoonLabs/astor#72]
# The problem
I tried to use ShortestIngredientSearchStrategy as ingredient strategy using '-ingredientstrategy'. But it gives me a ClassNotFoundException. However, there is no problem running the single test case "IngredientSpaceTest", where it also uses ShortestIngredientSearchStrategy.

# How to reproduce

```bash
git clone https://github.com/SpoonLabs/astor.git
cd astor
mvn clean compile
cd examples/Math-issue-280
mvn clean compile test
cd ../../
mvn dependency:build-classpath | egrep -v "(^\[INFO\]|^\[WARNING\])" | tee /tmp/astor-classpath.txt
java -cp $(cat /tmp/astor-classpath.txt):target/classes fr.inria.main.evolution.AstorMain -mode jGenProg -srcjavafolder examples/Math-issue-280/src/java/ -srctestfolder examples/Math-issue-280/src/test/  -binjavafolder examples/Math-issue-280/target/classes/ -bintestfolder examples/Math-issue-280/target/test-classes/ -location /Users/zimin/Desktop/KTH/Master-Thesis/Astor/astor/examples/Math-issue-280/ -dependencies examples/Math-issue-280/lib -ingredientstrategy fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.ShortestIngredientSearchStrategy
```

# Output from Astor

```bash
2018-03-12 10:31:20,192 INFO main - command line arguments: [-mode  jGenProg  -srcjavafolder  examples/Math-issue-280/src/java/  -srctestfolder  examples/Math-issue-280/src/test/  -binjavafolder  examples/Math-issue-280/target/classes/  -bintestfolder  examples/Math-issue-280/target/test-classes/  -location  /Users/zimin/Desktop/KTH/Master-Thesis/Astor/astor/examples/Math-issue-280/  -dependencies  examples/Math-issue-280/lib  -ingredientstrategy  fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.ShortestIngredientSearchStrategy]
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:810) - Source folders: [/Users/zimin/Desktop/KTH/Master-Thesis/Astor/astor/examples/Math-issue-280/src/java]
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:829) - Source Test folders: [/Users/zimin/Desktop/KTH/Master-Thesis/Astor/astor/examples/Math-issue-280/src/test]
[INFO ] fr.inria.astor.core.setup.ProjectConfiguration.addLocationToClasspath(ProjectConfiguration.java:140) - Adding to classpath junit-4.4.jar
[ERROR] fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:74) - Loading fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.ShortestIngredientSearchStrategy --java.lang.ClassNotFoundException: fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.ShortestIngredientSearchStrategy
Exception in thread "main" java.lang.Exception: Error Loading Engine: java.lang.ClassNotFoundException: fr.inria.astor.test.repair.evaluation.extensionpoints.ingredients.ShortestIngredientSearchStrategy
	at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:75)
	at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:64)
	at fr.inria.astor.approaches.ingredientbased.IngredientBasedPlugInLoader.loadIngredientSearchStrategy(IngredientBasedPlugInLoader.java:88)
	at fr.inria.astor.approaches.ingredientbased.IngredientBasedPlugInLoader.load(IngredientBasedPlugInLoader.java:135)
	at fr.inria.astor.core.loop.AstorCoreEngine.loadExtensionPoints(AstorCoreEngine.java:1017)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:107)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:172)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:228)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:205)
```

# How I run the IngredientSpaceTest

```bash
cd examples/math_85/
mvn clean compile test
cd ../..
mvn -Dtest=IngredientSpaceTest test
```

**Comment by martinezmatias** [comment]
Hi, 
The ShortestIngredientSearchStrategy is located in the test folder (it's a class for testing the ingredient strategy). So, in the command you have to include the path to the test class folder (target/test-classes). See that in the command you provided, it's not included
java -cp $(cat /tmp/astor-classpath.txt):target/classes fr.inria.main.evolution.AstorMain

**Comment by martinezmatias** [comment]
Hi @chenzimin 
> However, this time, it throws java.lang.NullPointerException in (ShortestIngredientSearchStrategy.java:53), which is:

Do you have more information about the issue?
I could not reproduce it.
Thanks!
Matias
